name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Test
        run: |
          npm install --legacy-peer-deps
          npm run lint

      - name: Add private key
        env:
          KEY: ${{ secrets.PRIVATE_KEY }}
        run: echo "$KEY" > key.pem

      - name: Build crx
        run: |
          npm run build
          npm run build:crx

      - uses: actions/upload-artifact@v4
        with:
          name: carbonx
          path: carbonx.crx
